version: "3"

services:
  api:
    build: .
    image: event-planner-api:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mongodb://database:27017/planner
      - SECRET_KEY=secretkey

  database:
    image: mongo
    ports:
      - "27017"
    volumes:
      - data:/data/db

volumes:
  data: